"""Generate paper/settings_table.typ from configs/models.toml — the exact
model strings and decoding settings table, never hand-typed."""

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
models = tomllib.loads((ROOT / "configs" / "models.toml").read_text())["models"]

rows = []
for mid, m in models.items():
    pin = ", ".join(m.get("provider_only", [])) or "unpinned"
    api = "Anthropic Messages" if m["api_path"] == "anthropic" else "chat completions"
    extra = f'thinking {m["thinking_budget"]}' if m.get("thinking_budget") else f'cap {m["max_completion_tokens"]}'
    rows.append(
        f'  [`{mid}`], [{pin}], [{api}], [{extra}], '
        f'[{m["price_in"]}], [{m["price_out"]}],'
    )

out = """// generated by gen_settings_table.py — do not edit
#table(
  columns: (auto, auto, auto, auto, auto, auto),
  align: (left, left, left, left, right, right),
  stroke: 0.4pt + rgb("#cccccc"),
  inset: 4.5pt,
  table.header([*model string*], [*provider pin*], [*API*], [*tokens*], [*\\$/1M in*], [*\\$/1M out*]),
%s
)
""" % "\n".join(rows)
(ROOT / "paper" / "settings_table.typ").write_text(out)
print("wrote paper/settings_table.typ")
